"""Generate ESP32 firmware config headers from root app config."""

from __future__ import annotations

import json
import os
import socket
import subprocess
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
EXAMPLE_CONFIG = ROOT / "config" / "app.example.json"
LOCAL_CONFIG = ROOT / "config" / "app.local.json"
CAMERA_HEADER = ROOT / "CameraWebServer" / "config.generated.h"
SENSOR_HEADER = ROOT / "ESP32_SensorNode" / "config.generated.h"


def deep_merge(base: dict[str, Any], override: dict[str, Any]) -> dict[str, Any]:
    result = dict(base)
    for key, value in override.items():
        if isinstance(value, dict) and isinstance(result.get(key), dict):
            result[key] = deep_merge(result[key], value)
        else:
            result[key] = value
    return result


def load_config() -> dict[str, Any]:
    with EXAMPLE_CONFIG.open() as f:
        config = json.load(f)
    if LOCAL_CONFIG.exists():
        with LOCAL_CONFIG.open() as f:
            config = deep_merge(config, json.load(f))
    config = apply_env_overrides(config)
    config["backend"]["host"] = resolve_backend_host(config["backend"]["host"])
    return config


def apply_env_overrides(config: dict[str, Any]) -> dict[str, Any]:
    env_map = {
        ("backend", "host"): ("BACKEND_HOST", str),
        ("backend", "port"): ("BACKEND_PORT", int),
        ("wifi", "ssid"): ("WIFI_SSID", str),
        ("wifi", "password"): ("WIFI_PASSWORD", str),
        ("firmware", "register_interval_ms"): ("BACKEND_REGISTER_INTERVAL_MS", int),
        ("firmware", "sensor_http_port"): ("SENSOR_HTTP_PORT", int),
        ("firmware", "camera_http_port"): ("CAMERA_HTTP_PORT", int),
        ("firmware", "camera_stream_port"): ("CAMERA_STREAM_PORT", int),
        ("firmware", "speaker_alert_duration_ms"): ("SPEAKER_ALERT_DURATION_MS", int),
        ("firmware", "alarm_check_interval_ms"): ("ALARM_CHECK_INTERVAL_MS", int),
    }
    for path, (env_name, caster) in env_map.items():
        raw = os.environ.get(env_name)
        if raw is None:
            continue
        section, key = path
        config.setdefault(section, {})[key] = caster(raw)
    return config


def resolve_backend_host(host: Any) -> str:
    host = str(host).strip()
    if host and host.lower() != "auto":
        return host

    detected = detect_lan_ip()
    if detected:
        return detected
    raise RuntimeError(
        "Could not auto-detect backend host IP. Set backend.host in "
        "config/app.local.json or BACKEND_HOST in the environment."
    )


def detect_lan_ip() -> str | None:
    detected = detect_lan_ip_with_socket()
    if detected:
        return detected
    for command in (
        ["ipconfig", "getifaddr", "en0"],
        ["ipconfig", "getifaddr", "en1"],
        ["ifconfig"],
        ["ip", "addr", "show"],
        ["hostname", "-I"],
    ):
        detected = detect_lan_ip_with_command(command)
        if detected:
            return detected
    return None


def detect_lan_ip_with_socket() -> str | None:
    try:
        with socket.socket(socket.AF_INET, socket.SOCK_DGRAM) as sock:
            sock.connect(("8.8.8.8", 80))
            ip = sock.getsockname()[0]
            return ip if not ip.startswith("127.") else None
    except OSError:
        return None


def detect_lan_ip_with_command(command: list[str]) -> str | None:
    try:
        result = subprocess.run(
            command,
            check=False,
            capture_output=True,
            text=True,
            timeout=2,
        )
    except (OSError, subprocess.SubprocessError):
        return None
    for token in result.stdout.replace("\n", " ").split():
        if is_ipv4(token) and not token.startswith("127."):
            return token
    return None


def is_ipv4(value: str) -> bool:
    parts = value.split(".")
    if len(parts) != 4:
        return False
    try:
        return all(0 <= int(part) <= 255 for part in parts)
    except ValueError:
        return False


def c_string(value: Any) -> str:
    return json.dumps(str(value))


def render_header(config: dict[str, Any], guard: str, include_camera_ports: bool) -> str:
    backend = config["backend"]
    wifi = config["wifi"]
    firmware = config["firmware"]

    lines = [
        f"#ifndef {guard}",
        f"#define {guard}",
        "",
        "// Generated by src.firmware_config.",
        "// Do not edit this file directly; edit config/app.local.json instead.",
        "",
        f"static const char* const WIFI_SSID = {c_string(wifi['ssid'])};",
        f"static const char* const WIFI_PASSWORD = {c_string(wifi['password'])};",
        f"static const char* const BACKEND_HOST = {c_string(backend['host'])};",
        f"static const int BACKEND_PORT = {int(backend['port'])};",
        "static const unsigned long BACKEND_REGISTER_INTERVAL_MS = "
        f"{int(firmware['register_interval_ms'])};",
    ]

    if include_camera_ports:
        lines.extend(
            [
                f"static const int HTTP_PORT = {int(firmware['camera_http_port'])};",
                f"static const int STREAM_PORT = {int(firmware['camera_stream_port'])};",
            ]
        )
    else:
        lines.extend(
            [
                f"static const int SENSOR_HTTP_PORT = {int(firmware['sensor_http_port'])};",
                "static const unsigned long ALARM_CHECK_INTERVAL_MS = "
                f"{int(firmware['alarm_check_interval_ms'])};",
                "static const unsigned long SPEAKER_ALERT_DURATION_MS = "
                f"{int(firmware['speaker_alert_duration_ms'])};",
            ]
        )

    lines.extend(["", f"#endif // {guard}", ""])
    return "\n".join(lines)


def generate_firmware_config(verbose: bool = True) -> tuple[Path, Path]:
    config = load_config()
    CAMERA_HEADER.write_text(
        render_header(config, "CAMERA_WEB_CONFIG_GENERATED_H", True)
    )
    SENSOR_HEADER.write_text(
        render_header(config, "SENSOR_NODE_CONFIG_GENERATED_H", False)
    )
    if verbose:
        print(f"Generated {CAMERA_HEADER.relative_to(ROOT)}")
        print(f"Generated {SENSOR_HEADER.relative_to(ROOT)}")
    return CAMERA_HEADER, SENSOR_HEADER
